Add HW 1
kjkrVdxB/Java-HW pull request #1
Opened 2019-01-22 00:36 UTC by kjkrVdxB

2019-01-23 18:44 UTC, kjkrVdxB commented
В текущий момент при удалении и очищении используемая память не освобождается. В ближайшее время поправлю.

2019-01-23 20:17 UTC, kjkrVdxB commented
На момент force-push прошло около минуты с коммита, так что верю, что проблем не будет.

2019-01-27 17:41 UTC, jzuken requested changes

2019-01-27 17:41 UTC, jzuken commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +/**
однострочные доки лучше так и писать в одну строку: `/** ... */`

2019-01-27 17:41 UTC, jzuken commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +    final private static int INVERSE_PUT_REHASH_THRESHOLD = 2;
смотрю на эти имена и ничего не понимаю. возможно не помешал бы комментарий, либо более понятные имена

2019-01-27 17:41 UTC, jzuken commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +    public String put(String key, String value) {
а аргументы вполне могут быть null

2019-01-27 17:41 UTC, jzuken commented on hashtable/src/main/java/com/example/hashtable/KeyValueList.java
> +    public class Link {
а он кому-то нужен за пределами списка?

2019-01-27 19:19 UTC, kjkrVdxB commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +    public String put(String key, String value) {
Да. Я разрешил и key и value быть равным null, они корректно обрабатываются. Но по заданию здесь при отсутствии ключа надо возвращать null. Поэтому задокументировано, что возникает неопределённость, которую можно избежать вызовом contains, который всегда корректно отвечает. Лучше запретить value быть равным null?

2019-01-27 19:21 UTC, kjkrVdxB commented on hashtable/src/main/java/com/example/hashtable/KeyValueList.java
> +    public class Link {
Да. В HashTable.rehash(int) он используется, чтобы перебрать весь список.

2019-01-27 19:49 UTC, jzuken commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +    public String put(String key, String value) {
думаю, да. и бросать исключение, когда нуллы всё же передаются

2019-01-27 19:49 UTC, jzuken commented on hashtable/src/main/java/com/example/hashtable/KeyValueList.java
> +    public class Link {
а это уже похоже на раскрытие деталей реализации. там для обхода списка лучше бы подошёл итератор

2019-01-27 22:26 UTC, kjkrVdxB commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +    public String put(String key, String value) {
Сделано

2019-01-27 22:27 UTC, kjkrVdxB commented on hashtable/src/main/java/com/example/hashtable/KeyValueList.java
> +    public class Link {
Сделал Link private. Добавил публичный Entry. Вместо getHead теперь есть popFirst.

2019-01-27 22:28 UTC, kjkrVdxB commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +    final private static int INVERSE_PUT_REHASH_THRESHOLD = 2;
Добавил комментарии

2019-01-27 22:28 UTC, kjkrVdxB commented on hashtable/src/main/java/com/example/hashtable/HashTable.java
> +/**
Исправлено

2019-02-11 14:49 UTC, jzuken commented
а можно мне сюда доступ на запись?

2019-03-17 18:03 UTC, merged