Add HW8 (Cannon)
kjkrVdxB/Java-HW pull request #11
Opened 2019-05-21 20:11 UTC by kjkrVdxB

2019-05-31 10:11 UTC, RamSaw requested changes
@kjkrVdxB проверил. крутая архитектура и графика, но видимо раз кода много, то и комментировать есть что :)

2019-05-31 10:11 UTC, RamSaw commented on cannon/build.gradle
> +mainClassName = 'com.example.cannon.CannonApplication'
jar не запускается

2019-05-31 10:11 UTC, RamSaw commented on cannon/settings.gradle
> +rootProject.name = 'cannon'
очень крутая графика, респект :)
Но я пока играл словил exception, но правда на работу игры он вроде повлиял, пофиксите его, пожалуйста, это вообще я вижу ваше исключение:
`Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Trying to access World while not registered
        at com.example.cannon.game.GameEntity.getWorld(GameEntity.java:16)
        at com.example.cannon.entity.BasicProjectile.update(BasicProjectile.java:57)
        at com.example.cannon.entity.Weapon$FunkyBombBuilder$1$1.update(Weapon.java:131)
        at com.example.cannon.game.World.entityUpdateLoop(World.java:81)
        at com.example.cannon.game.World.update(World.java:68)
        at com.example.cannon.game.Game.handle(Game.java:151)
        at javafx.graphics/javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:57)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
        at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
        at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:558)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:542)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:535)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:341)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Trying to access World while not registered
        at com.example.cannon.game.GameEntity.getWorld(GameEntity.java:16)
        at com.example.cannon.entity.Weapon$FunkyBombBuilder$1$1.update(Weapon.java:128)
        at com.example.cannon.game.World.entityUpdateLoop(World.java:81)
        at com.example.cannon.game.World.update(World.java:68)
        at com.example.cannon.game.Game.handle(Game.java:151)
        at javafx.graphics/javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:57)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
        at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
        at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:558)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:542)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:535)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:341)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:834)`

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/CannonApplication.java
> +            new Game(root, new SimpleWorldLoader(filename), onFinishCalBack).start();
Callback*

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/SimpleWorldGenerator.java
> +            if (i == 330) {
давайте выделим в переменные числа 330 и 50

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/SimpleWorldGenerator.java
> +public class SimpleWorldGenerator {
javadoc бы с описанием формата и структуры генерируемого файла

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/SimpleWorldLoader.java
> +        scanner.close();
try with resources?

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/BasicProjectile.java
> +        return position.getX() + radius <= -WIDTH / 2 || position.getX() - radius >= WIDTH * 1.5;
а зачем так долго ждать? можно же сразу как она вылетела за пределы по X говорить, что она out of bounds.

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/BasicProjectile.java
> +        graphicsContext.restore();
а зачем делать save/restore? если это как-то зависит от того, какие объекты перекрывают другие, то наверное это должно быть завязано на текущий drawing layer.

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/Cannon.java
> +    private int angleMovingDirection;
enum? к обоим direction

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/Cannon.java
> +        graphicsContext.restore();
давайте выделим методы из этого большого метода. Чтобы сразу было видно, где рисуются колеса, где пушка и так далее. Так потом код поддерживать гораздо легче будет.

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/Drawable.java
> +    void draw(@NonNull GraphicsContext graphicsContext);
вообще если вы хотите поддержать постоянный инвариант, что save; myCode; restore; то можно навесить декоратор тут и код дублироваться не будет. https://en.wikipedia.org/wiki/Decorator_pattern

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/Terrain.java
> +    private void trySubdivide(double x) {
а зачем так делать? почему сразу не нагенерить нужное количество точек?

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/Terrain.java
> +    // Math utils specific for terrain. */
/** ... */

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/Weapon.java
> +public interface Weapon {
давайте может интерфейс здесь оставим, а Builders перенесем в другие файлы, а то как-то очень много кода в одном файле и читать трудно.

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/game/Game.java
> +        selectWeapon(3); // Default weapon
в переменную

2019-05-31 10:11 UTC, RamSaw commented on cannon/src/test/java/com/example/cannon/TerrainTest.java
> +class TerrainTest {
ну Вы либо тестов напишите, либо файл удалите.

2019-05-31 23:31 UTC, kjkrVdxB commented on cannon/src/test/java/com/example/cannon/TerrainTest.java
> +class TerrainTest {
Убрал файл. Разрешили не писать тесты.

2019-05-31 23:32 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/game/Game.java
> +        selectWeapon(3); // Default weapon
Сделано.

2019-05-31 23:32 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/Terrain.java
> +    // Math utils specific for terrain. */
На самом деле //, потому что этот коментарий отделяет секцию, а не приставлен к конкретной функции. Поправил.

2019-05-31 23:34 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/Terrain.java
> +    private void trySubdivide(double x) {
Идея в том чтобы те кто делает карту не думали об этом. Нужно это кстати для взрывов: если есть длинный отрезок, то небольшой взрыв посреди него никак не повлияет на землю. Тут Terrain гарантирует, что с некоторой точностью такого не будет.

2019-05-31 23:38 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/SimpleWorldGenerator.java
> +public class SimpleWorldGenerator {
На самом деле эти generator и loader писались не то чтобы для того чтобы их потом читали. По заданию карту достаточно было сделать фиксированной и эта фиксированная карта лежит в репозитории. Можно впринципе считать, что этих классов здесь нет. Хороший формат уровней и правда наверно круто бы продумать, но уже лень было.

2019-05-31 23:40 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/BasicProjectile.java
> +        return position.getX() + radius <= -WIDTH / 2 || position.getX() - radius >= WIDTH * 1.5;
Ну например если Funky Bomb вылетает за пределы карты у неё есть немного возможности взорваться и "вернуть" ещё бомб на поле. Понятие "далеко" правда достаточно произвольное тут выбрано.

2019-05-31 23:42 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/CannonApplication.java
> +            new Game(root, new SimpleWorldLoader(filename), onFinishCalBack).start();
Поправил.

2019-05-31 23:45 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/SimpleWorldGenerator.java
> +            if (i == 330) {
Там дальше написано, этот скрипт и правда написан на коленке, он так сказать "на один запуск". Предполагалось его вообще не выкладывать, но подумал что не помешает. Может чуть позже его причешу, но не уверен что это имеет много смысла.

2019-05-31 23:47 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/BasicProjectile.java
> +        graphicsContext.restore();
Drawing layer это больше про то что над чем рисуется. Это не про перекрывания, а больше про состояние GraphicsContext, хочется чтобы когда я его передаю его мне вернули в исходном состоянии.

2019-05-31 23:51 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/Drawable.java
> +    void draw(@NonNull GraphicsContext graphicsContext);
Там немного труднее, save/restore в принципе может быть не достаточно. Тут скорее про требование от тех, кто делает draw, выполнение этого требования на их совести.

2019-06-01 00:17 UTC, kjkrVdxB commented on cannon/settings.gradle
> +rootProject.name = 'cannon'
Исправил.

2019-06-01 00:31 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/Cannon.java
> +        graphicsContext.restore();
Сделано.

2019-06-01 00:36 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/Drawable.java
> +    void draw(@NonNull GraphicsContext graphicsContext);
Отразил сказанное в документации.

2019-06-01 00:43 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/Weapon.java
> +public interface Weapon {
Сделано.

2019-06-01 01:13 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/entity/Cannon.java
> +    private int angleMovingDirection;
Сделано.

2019-06-01 14:09 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/SimpleWorldLoader.java
> +        scanner.close();
Сделано.

2019-06-01 14:09 UTC, kjkrVdxB commented on cannon/src/main/java/com/example/cannon/SimpleWorldGenerator.java
> +public class SimpleWorldGenerator {
Добавил описание формата в SimpleWorldLoader

2019-06-04 12:11 UTC, RamSaw commented on cannon/settings.gradle
> +rootProject.name = 'cannon'
В чем ошибка была?

2019-06-04 12:19 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/SimpleWorldGenerator.java
> +public class SimpleWorldGenerator {
тогда надо было просто не выкладывать в git эти файлы и все

2019-06-04 12:20 UTC, RamSaw commented on cannon/src/main/java/com/example/cannon/entity/BasicProjectile.java
> +        return position.getX() + radius <= -WIDTH / 2 || position.getX() - radius >= WIDTH * 1.5;
ладно, раз работает пусть будет так

2019-06-04 12:32 UTC, RamSaw approved these changes
@kjkrVdxB все ок.
@jzuken

2019-06-05 00:36 UTC, kjkrVdxB commented on cannon/settings.gradle
> +rootProject.name = 'cannon'
Фикс здесь: a490f49747
Там идея в том, что после explode (который вызывает disappear, который разрегистрирует из мира) обращатся к миру уже нельзя. А тут он Funky Bomb вызывал родительский update даже после explode.

2019-06-05 01:56 UTC, kjkrVdxB commented on cannon/build.gradle
> +mainClassName = 'com.example.cannon.CannonApplication'
Исправил.

2019-06-06 08:00 UTC, merged