Add HW9 (Unit)
kjkrVdxB/Java-HW pull request #13
Opened 2019-06-02 13:20 UTC by kjkrVdxB

2019-06-07 17:53 UTC, jzuken requested changes

2019-06-07 17:53 UTC, jzuken commented on unit/src/main/java/com/example/unit/api/Test.java
> +public @interface Test {
доки?
-1

2019-06-07 17:53 UTC, jzuken commented on unit/src/main/java/com/example/unit/UnitTestCli.java
> +    private static void usage() {
это не особо каноническое имя для метода

2019-06-07 17:53 UTC, jzuken commented on unit/src/main/java/com/example/unit/test/TestTest.java
> +public class TestTest {
этот класс надо к тестам положить, тут он не нужен совсем
-0.5

2019-06-07 17:53 UTC, jzuken commented on unit/src/main/java/com/example/unit/UnitTestRunner.java
> +        return Arrays.stream(unitTests.getDeclaredMethods()).filter(method -> method.getAnnotation(annotation) != null).collect(Collectors.toList());
длинновата строка

2019-06-07 17:53 UTC, jzuken commented on unit/src/main/java/com/example/unit/UnitTestRunner.java
> +        this.beforeMethods = getMethodsAnnotatedWith(Before.class);
а ещё было бы неплохо проверить, что на метод не навешали больше, чем надо

2019-06-07 17:53 UTC, jzuken commented on unit/src/test/java/com/example/unit/UnitTestRunnerTest.java
> +    static class Test3 {
я бы убрал их в отдельные файлы, чтобы они не засоряли тесты

2019-06-08 17:54 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/UnitTestCli.java
> +    private static void usage() {
Исправлено.

2019-06-08 17:55 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/test/TestTest.java
> +public class TestTest {
Не соглашусь. Он там лежит чтбы его можно было протестировать в консоли с помощью
`gradle run --args com.example.unit.test.TestTest`

2019-06-08 17:56 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/UnitTestRunner.java
> +        return Arrays.stream(unitTests.getDeclaredMethods()).filter(method -> method.getAnnotation(annotation) != null).collect(Collectors.toList());
Исправлено.

2019-06-08 18:00 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/UnitTestRunner.java
> +        this.beforeMethods = getMethodsAnnotatedWith(Before.class);
Не понял. У меня проверяется, что на `@Test` методах не висит ещё и `@Before` или `@After` (потому что это странно). Вы про другие аннотации? Почему нужно на них проверять, они же могут иметь своё значение, которое прохождению тестов не мешает? (`@Override` как пример, хотя не самый лучший)

2019-06-08 18:02 UTC, kjkrVdxB commented on unit/src/test/java/com/example/unit/UnitTestRunnerTest.java
> +    static class Test3 {
Не уверен. Там всё таки в тестах есть числа, оторые завязаны на этих классах. Когда класс прямо рядом с тестом сразу понятно, что эти числа значат. А так предётся туда-суда на два файла смотреть.

2019-06-08 18:08 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/api/Test.java
> +public @interface Test {
Исправлено.

2019-06-10 07:30 UTC, jzuken commented on unit/src/main/java/com/example/unit/test/TestTest.java
> +public class TestTest {
ну когда вы делаете jar-ник для продакшена, туда не попадает ничего из папки test, а вот этот товарищ там зачем-то будет, хотя к боевому коду он никакого отношения не имеет

2019-06-10 07:31 UTC, jzuken commented on unit/src/main/java/com/example/unit/UnitTestRunner.java
> +        this.beforeMethods = getMethodsAnnotatedWith(Before.class);
BeforeAll, например, вместе с Test

2019-06-10 07:31 UTC, jzuken commented on unit/src/test/java/com/example/unit/UnitTestRunnerTest.java
> +    static class Test3 {
ну ок, пусть останутся

2019-06-10 10:51 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/UnitTestRunner.java
> +        this.beforeMethods = getMethodsAnnotatedWith(Before.class);
Такого не бывает, проверяется что `@BeforeAll` стоят на статических, а `@Test` - на не статических.

2019-06-10 11:06 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/test/TestTest.java
> +public class TestTest {
В каком-то смысле имеет - это пример запуска CLI. Может и не очень хорошо, что он внутри jarника, но он точно нужен не только тестам.

2019-06-10 13:56 UTC, kjkrVdxB commented on unit/src/main/java/com/example/unit/test/TestTest.java
> +public class TestTest {
Перенёс.

2019-06-12 09:37 UTC, merged