Add FTPGUI HW
kjkrVdxB/Java-HW pull request #14
Opened 2019-06-05 03:10 UTC by kjkrVdxB

2019-06-09 09:07 UTC, RamSaw commented
@lyubortk @kjkrVdxB а почему вы домашку вместе делали?

2019-06-09 09:18 UTC, RamSaw commented
@lyubortk @kjkrVdxB 
так, я узнал, что вы все в парах дз делали. Но почему тогда у Вас на hwproj у обоих сдано? @lyubortk Вы у себя кинули ссылку на этот PR тоже?

2019-06-09 10:10 UTC, RamSaw requested changes
@kjkrVdxB проверил.
-1 за невозможность сборки и запуска сервера с помощью gradle.
+1 за джавдоки хорошие, хорошую архитектуру по части работы с JavaFX и за тесты.
В общем в ноль вышли :)

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/build.gradle
> +mainClassName = 'com.example.ftpgui.FTPClientGUI'
ок, клиент я могу запустить ./gradlew run
а сервер как запустить?

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/settings.gradle
> +rootProject.name = 'ftpgui'
когда сервер не запущен он connecting бесконечно долго. Давайте попробуем timeOut сделать и выдавать сообщение, что сервер недоступен.

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPClient.java
> +        return socket != null && socket.isConnected();
а гарантируется, что если isConnected = false, то close можно не вызывать?

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPClient.java
> +
строка

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +    private static final int LISTVIEW_ITEM_TEXT_GAP = 20;
LIST_VIEW

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +
строка

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +public class FTPClientGUI extends Application {
God Class какой-то получился. Конечно для GUI это стандартный антипаттерн, с которым трудно бороться, но посмотрите, может быть сможете выделить какие-то разумные сущности. Handler'ы всякие к примеру можно выделить в новый класс. Там же есть какая-то обособленная логика.

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +        pauseTransition = new PauseTransition(Duration.millis(DELAY_MILLIS));
а зачем PauseTransition?

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                for (; ; ) {
while (true)?

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +        worker = new Thread(() -> {
выделите код внутри try'ев и if'ов в методы, чтобы код был более читаем.

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                // time to go out
println("Exiting...")?

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +        worker.interrupt();
кажется в worker вы нигде не ловите InterruptedException.

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +    private class ChannelHandler {
в отдельный файл

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                        // Basic protection against DOS
DOS?

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                            // ???
???

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                        // well we go now
???

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/TestClient.java
> +public class TestClient {
Test? почему тест и не в директории test?

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/main/java/com/example/ftpgui/TestServer.java
> +        var server = new FTPServer(9999);
не надо хардкодить порт. А если он у меня занят? Сделайте дефолтный порт и возможность указать свой, если надо.

2019-06-09 10:10 UTC, RamSaw commented on ftpgui/src/test/java/com/example/ftpgui/FTPTest.java
> +    private static class SimpleServer {
это моками делается тогда уж, но да ладно, Вы тестов много хороших написали, пусть будет так.
Сделайте только название класса такое, чтобы было понятно, что вы тестируете конкрентно. Клиента или сервер, или все вместе сразу. И джавадок добавьте.
Как я понимаю, первые тесты это все вместе, последние только на клиент. Тогда надо разбить этот класс на два.

2019-06-09 10:36 UTC, RamSaw commented
@kjkrVdxB еще кстати, почему вы выбрали писать на селекторах, а не на обычных блокирующих сокетах? Мне кажется, проще было бы просто каждого клиента в свой поток отправлять и там с ним работать в блокирующем режиме.

2019-06-10 10:56 UTC, kjkrVdxB commented
> @kjkrVdxB еще кстати, почему вы выбрали писать на селекторах, а не на обычных блокирующих сокетах? Мне кажется, проще было бы просто каждого клиента в свой поток отправлять и там с ним работать в блокирующем режиме.

Дак это же часть задания.

2019-06-10 10:57 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                        // well we go now
Если `ClosedChannelException`, то этому потоку пора завершаться, что здесь и написано.

2019-06-10 10:57 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                for (; ; ) {
Это всё же личное предпочтение как мне кажется.

2019-06-10 10:58 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                        // Basic protection against DOS
Denial of Service.

2019-06-10 11:01 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +        worker.interrupt();
На самом деле это должно влиять на селектор, так в документации написано.

2019-06-10 11:24 UTC, lyubortk commented
> @lyubortk @kjkrVdxB
> так, я узнал, что вы все в парах дз делали. Но почему тогда у Вас на hwproj у обоих сдано? @lyubortk Вы у себя кинули ссылку на этот PR тоже?

Да, там тот же PR

2019-06-10 11:31 UTC, kjkrVdxB commented on ftpgui/settings.gradle
> +rootProject.name = 'ftpgui'
Исправлено.

2019-06-10 11:37 UTC, lyubortk commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +        pauseTransition = new PauseTransition(Duration.millis(DELAY_MILLIS));
Надо отложить исполнение операций некоторых. В том числе я использую это, чтобы показать какое-нибудь сообщение об ошибке в нижней строке на несколько секунд.

2019-06-10 11:47 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/TestServer.java
> +        var server = new FTPServer(9999);
Это были крайне простые примеры запуска. Убрал их, добавил нормальный CLI для сервера.

2019-06-10 11:47 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/TestClient.java
> +public class TestClient {
См ниже

2019-06-10 11:48 UTC, kjkrVdxB commented on ftpgui/build.gradle
> +mainClassName = 'com.example.ftpgui.FTPClientGUI'
Исправлено.
`gradle runServer --args <port>`

2019-06-10 11:50 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPClient.java
> +
Исправлено.

2019-06-10 11:51 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                // time to go out
Сделано.

2019-06-10 11:57 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +    private class ChannelHandler {
Он всё же тесно связан с сервером (ему например нужно оперировать с пулом). А вот `RequestHandler` вынес в отдельный файл.

2019-06-10 14:14 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +        worker = new Thread(() -> {
Он был довольно компактный и выделен по возможности. Выделил все `printStackTrace()` в отдельную функцию чтобы этим выводом можно было в одном месте управлять.

2019-06-10 14:15 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPServer.java
> +                            // ???
Поправил.

2019-06-10 14:23 UTC, kjkrVdxB commented on ftpgui/src/main/java/com/example/ftpgui/FTPClient.java
> +        return socket != null && socket.isConnected();
Почитал документацию. Там написано, что `isConnected` немного не про то на самом деле, поэтому переделал, хотя оно впринципе работало.

2019-06-10 14:34 UTC, kjkrVdxB commented on ftpgui/src/test/java/com/example/ftpgui/FTPTest.java
> +    private static class SimpleServer {
Разбил на три.

2019-06-10 14:38 UTC, kjkrVdxB commented
> Но почему тогда у Вас на hwproj у обоих сдано?

Чтобы было понятно разделение на пары без необходимости лезть в коммиты. Ну и когда на hwproj пусто то не понятно, это человек совсем на задание забил и не делал или просто не он PR делает.

2019-06-10 14:40 UTC, lyubortk commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +    private static final int LISTVIEW_ITEM_TEXT_GAP = 20;
Исправил

2019-06-10 14:41 UTC, lyubortk commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +
Исправил

2019-06-10 14:41 UTC, lyubortk commented on ftpgui/src/main/java/com/example/ftpgui/FTPClientGUI.java
> +public class FTPClientGUI extends Application {
Разделил на два класса в папке gui (вынес хэндлеры в отдельный класс).

2019-06-10 14:46 UTC, kjkrVdxB commented
@RamSaw Вроде всё поправили.

2019-06-13 10:08 UTC, RamSaw approved these changes
@kjkrVdxB @lyubortk все ок.
@jzuken

2019-06-13 12:31 UTC, merged