Add HW2
kjkrVdxB/Java-HW pull request #2
Opened 2019-01-27 22:49 UTC by kjkrVdxB

2019-02-11 14:59 UTC, jzuken requested changes

2019-02-11 14:59 UTC, jzuken commented on trie/src/main/java/com/example/trie/Trie.java
> +        root = new Node();
это лучше сделать при объявлении поля

2019-02-11 14:59 UTC, jzuken commented on trie/src/test/java/com/example/trie/TrieTest.java
> +        assertThrows(IllegalArgumentException.class, () -> testTrie.add(null));
давайте сделаем более гранулярные тесты, ну чтобы каждый из них проверял что-то одно. а то у вас всё в кучу, и если что-то пойдёт не так, скорее всего все тесты развалятся сразу

2019-02-11 14:59 UTC, jzuken commented on trie/src/test/java/com/example/trie/TrieTest.java
> +    void testSerializeDeserialize() {
ну по факту этот тест проверяет, что сериализатор и десериализатор работают одинаково. и если там, например, будет одинаковая симметричная ошибка, то вы этого не поймаете. хочется отдельные тесты на проверку каждого из них

2019-02-11 18:20 UTC, kjkrVdxB commented on trie/src/test/java/com/example/trie/TrieTest.java
> +    void testSerializeDeserialize() {
Но ведь формат сериализации не входит в публичный интерфейс. Тогда не понятно как проверять отдельно сериализацию.

2019-02-11 18:26 UTC, kjkrVdxB commented on trie/src/test/java/com/example/trie/TrieTest.java
> +        assertThrows(IllegalArgumentException.class, () -> testTrie.add(null));
Не очень понятно, как проверять их отдельно. Если проверять первым только add, то мы не узнаем, что он реально добавляет что-то (то, что он возвращает, по сути, то, что вернул бы contains, конечно, спасает, но если бы он этого не делал, то вообще ничего проверить нельзя было бы). contains без add вообще не проверить, т.к. add -- единственный способ сделать Trie непустым. Или можно разрешить им друг другом пользоваться и при этом тестировать только один из них?

2019-02-11 18:37 UTC, kjkrVdxB commented on trie/src/main/java/com/example/trie/Trie.java
> +        root = new Node();
Исправлено.

2019-02-12 09:40 UTC, jzuken commented on trie/src/test/java/com/example/trie/TrieTest.java
> +    void testSerializeDeserialize() {
что значит не входит? это наблюдаемое извне поведение объекта. 
проверять понятно как: пишете в массив, потом проверяете, что всё записалось как надо

2019-02-16 18:26 UTC, kjkrVdxB commented on trie/src/test/java/com/example/trie/TrieTest.java
> +        assertThrows(IllegalArgumentException.class, () -> testTrie.add(null));
Попытался исправить.

2019-03-07 11:39 UTC, jzuken commented on trie/src/main/java/com/example/trie/Trie.java
> +    private static void serializeTree(Node node, DataOutputStream dataOut) throws IOException {
ну всё же принято сначала размещать более доступные члены класса, а так вот начинать с приватных не стоит

2019-03-07 11:39 UTC, merged