Add HW3
kjkrVdxB/Java-HW pull request #3
Opened 2019-02-03 14:13 UTC by kjkrVdxB

2019-02-25 16:30 UTC, RamSaw requested changes
@kjkrVdxB домашку проверил, жду исправлений или контраргументов.

2019-02-25 16:30 UTC, RamSaw commented on treeset/build.gradle
> +}
Аннотации видимо не будут использоваться, а надо бы.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> + *
зачем здесь пустая строчка?

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private int compare(Object a, Object b) {
Тут же можно передавать b как тип E. И кастить лишний раз не нужно будет. Но более того, важно то, что вы вызывать compareTo должны у Object, который вам передали, а не у элемента в дереве. Поэтому важно различать их: один Object, другой E.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return new DescendingTreeSet<>(this);
Сделайте этот класс просто вложенным и не надо будет передавать this.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/NavigableSet.java
> +    /** {@link java.util.NavigableSet#descendingIterator} */
Вообще Вас просили сделать все как в TreeSet.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            throw new IllegalArgumentException("null elements are prohibited");
В TreeSet они не запрещены. Это касается всех случаев, добавьте пожалуйста поддержку null.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    public E floor(E e) {
кажется у Вас floor и lower ничем не отлючаются. Выделите вообще код этих 4 (еще ceiling and higher) похожих методов в один метод.

У Вас тут ошибки есть:
        TreeSet<Integer> t = new TreeSet<>();
        t.add(10);
        t.add(11);
        assertEquals(10, (int) t.floor(10));
        assertEquals(11, (int) t.lower(10));
Такое к примеру падает. Добавьте тогда еще тестов, более хороших, раз текущие упустили ошибку. На все 4 метода.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class Node<NodeE> {
Дженериком его делать необязательно.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class TreeSetIterator<ItE> implements Iterator<ItE> {
Нет, давайте лучше без наследования. И protected поля сделаем private.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class TreeSetIterator<ItE> implements Iterator<ItE> {
И дженерики уберем.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +     * because we want a wrapper around existing TreeSet object that can coexist with it.
Ну он и так будет coexist. Не очень понял аргумента.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +     * because we want a wrapper around existing TreeSet object that can coexist with it.
Более того, он у Вас приватный, его никто сам не сможет создать, передав туда не this, а свое дерево.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/DescendingTreeSetTest.java
> +class DescendingTreeSetTest extends TreeSetTest {
Наследование в тестах не самая лучшая практика. Но думаю здесь сойдет.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +    protected NavigableSet<Integer> testSet;
package-private

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +    void testContains() {
Contains не просто так принимает Object, протестируйте это. И у remove тоже.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +    void testFirstLast() {
Вообще лучше тестировать каждый метод по отдельности. Это всех тестов касается.

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertThrows(NoSuchElementException.class, () -> emptySet.first());
emptySet::first

2019-02-25 16:30 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertThrows(NoSuchElementException.class, () -> emptySet.first());
Всех других случаев тоже касается.

2019-02-25 17:36 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +     * because we want a wrapper around existing TreeSet object that can coexist with it.
Имеется в виду возможность существовать одновременно в программе. Пример этого можно увидеть в тесте testDescendingSet(). Такое поведение требуется oт descendingSet() в оригинальном NavigableSet:
_Returns a reverse order view of the elements contained in this set. The descending set is backed by this set, so changes to the set are reflected in the descending set, and vice-versa._ 
Для получения такого эффекта нужен в каком-то месте уровень косвенности. Я решил сделать так же, как, если я правильно понял, сделано в OpenJDK.
Там он раньше реально наследовался от TreeSet, это конечно была опечатка, сейчас он, как и должен, наследуется от AbstractSet.

2019-02-25 17:46 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertThrows(NoSuchElementException.class, () -> emptySet.first());
Это осмысленное решение. Мне кажется, что в таких местах, как `assertThrows` лучше всегда использовать лямбду для единообразия. Иначе странно выглятит, в одном месте
`assertThrows(..., () -> testSet.remove(null))`
, a в другом
`assertThrows(..., emptySet::first)`
Лямбда явно показывает, что мы хотим исполнить такое-то выражение, но "отложенно". С ссылками на методы эта семантика не так очевидна с первого взгляда.

2019-02-25 17:55 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> + *
Пустая строка после описания, когда после него идут дополнительные тэги, если я не ошибаюсь, всегда ставиться.

2019-02-25 17:56 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class TreeSetIterator<ItE> implements Iterator<ItE> {
Без наследования же уйма кода будет повторяться.

2019-02-25 18:00 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/NavigableSet.java
> +    /** {@link java.util.NavigableSet#descendingIterator} */
Это по поводу ссылки? В самом java.util.TreeSet JavaDoc копируется из java.lang.NavigableSet, поэтому вроде логичнее сразу на него ссылаться.

2019-02-25 18:22 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class Node<NodeE> {
Он вложенный и делать его внутренним вреде безполезно, так что без параметра типа вроде не обойтись.

2019-02-25 18:37 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +     * because we want a wrapper around existing TreeSet object that can coexist with it.
Сделал его внутренним, чтобы явно не хранить ссылку.

2019-02-25 18:38 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class TreeSetIterator<ItE> implements Iterator<ItE> {
Дженерики убрал.

2019-02-25 18:38 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return new DescendingTreeSet<>(this);
Сделал.

2019-02-25 18:56 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +    protected NavigableSet<Integer> testSet;
Сделал. Но `protected` тоже вроде логично, вдруг кто ещё захочет тестов отнаследовать (мне же захотелось). Но раз уж это не такая распространённая практика, то пусть будет.

2019-02-25 19:09 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +    void testFirstLast() {
Очень странно, что они здесь вместе. Конечно, должны быть отдельно. Исправлено.

2019-02-25 19:20 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    public E floor(E e) {
Не очень понял. Оно и должно падать, так как `t.lower(10)` возвращает `null` (как и должен), который потом кастится к `int`, и падает. Вроде всё правильно.
Отличия в них явно есть. Как их все в один метод объеденить я не очень понимаю, скорее всего в нём будет очень много `if`.

2019-02-25 19:25 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            throw new IllegalArgumentException("null elements are prohibited");
Про стандартный `TreeSet` в задании явно сказано не было. `null` запрещён из соображений о неоднозначноти возвращаемых значений `floor` и подобных. В ближайшее время поправлю.

2019-02-25 20:41 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            throw new IllegalArgumentException("null elements are prohibited");
Замечу, что в `TreeSet` они запрещены в случае, если используется естественный порядок.

2019-02-25 20:47 UTC, kjkrVdxB commented on treeset/build.gradle
> +}
Да, у меня к ним некоторая неприязнь. Как я понимаю, они не обязательны.
Проблема в том, что, если я правильно понимаю, они не могут влиять на рантайм поведение программы, а поэтому для проверки параметров внешнего интерфейса, например, они не подходят.
С другой стороны, все статические проверки кода ложатся на среду разработки, что в некотором смысле привязывает программу к этой среде.

2019-02-25 23:06 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    public E floor(E e) {
Объединил в один метод.

2019-02-26 06:28 UTC, RamSaw commented on treeset/build.gradle
> +}
У Вас же была уже лекция объясняющая, чем они хороши. 
https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html.
NotNull к примеру влияет на поведение программы в рантайм, потому что добавляет ассерты. 
Безусловно, если вы программируете не в Идеи, то Вам не подсветят желтым место, где Вы NPE можете схватить, но в рантайме вы упадете и это хорошо. 
Плюс большой в том, что это сокращает код (очевидные ассерты генерятся сами).
Я соглашусь с Вами, если Вы предложите какой-то более лучший способ проверки nullability (перейти на Котлин не считается :) ) или же приведете аргумент почему их НЕ стоит использовать.
Пока что очевидно, что использовать аннотации лучше, чем не использовать.

2019-02-26 06:30 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> + *
а ок, я ошибся

2019-02-26 06:32 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/NavigableSet.java
> +    /** {@link java.util.NavigableSet#descendingIterator} */
Я просто посмотрел интерфейс, который Вас просили реализовать и там ссылки на TreeSet. Ну ладно, он действительно имплементит NavigableSet и это не так важно,

2019-02-26 06:33 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            throw new IllegalArgumentException("null elements are prohibited");
Про естественный порядок это правда.

2019-02-26 06:40 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    public E floor(E e) {
Да, Вы правы, тест я неправильный Вам подкинул. 
Теперь вроде все ок.

2019-02-26 06:52 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +                if (!reverse) {
мне кажется лучше тут тернарный оператор использовать

2019-02-26 06:52 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +                if (!reverse) {
и выше тоже

2019-02-26 06:52 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class Node<NodeE> {
Мне просто кажется, что раз тип E уже известен, то не нужно его повторять, увеличивая тем самым вариативность (можно же и не E туда положить). То, что он не вызывает this у TreeSet это правда, но ведь мы должны гаранировать, что он хранит E и это всегда тот E, что у TreeSet.

2019-02-26 06:56 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class TreeSetIterator<ItE> implements Iterator<ItE> {
Если уж Вы очень хотите оставить наследование, то сделайте абстрактный BaseIterator, в котором будут hasNext и remove. 
А вообще можно просто передавать flag, reverse или не reverse и все.

2019-02-26 06:58 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +     * because we want a wrapper around existing TreeSet object that can coexist with it.
Про view это все правильно, да. Ок, мне нравится.

2019-02-26 07:01 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +    protected NavigableSet<Integer> testSet;
Почитайте про то, как избегать наследования в JUnit5. Там есть всякие Fixtures и другие вещи, которые более приспособлены для тестов.

2019-02-26 07:02 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertThrows(NoSuchElementException.class, () -> emptySet.first());
что значит "отложенно"?

2019-02-26 07:22 UTC, RamSaw requested changes
@kjkrVdxB исправления проверил, откомментил.

2019-02-26 07:22 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        var singletonTestSet = new TreeSet<String>((a, b) -> 0);
добавьте тестов на компаратор, поддерживающий null.

2019-02-26 07:22 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertFalse(testSet.contains("9"));
А зачем Вы все перенесли на строки?
https://github.com/kjkrVdxB/Java-HW/pull/3#discussion_r259904890
Когда я писал об этом, я имел в виду, что допустим есть такая иерархия: A implements Comparable<A>, B extends A, C extends A.
Потом мы в contains передаем C, а дерево у нас содержит B. Но при этом contains выдаст что-то осмысленное, потому что компаратор опеределен в их общем классе родителе.
Для remove тоже самое.

2019-02-26 11:05 UTC, kjkrVdxB commented on treeset/build.gradle
> +}
Мне казалось, что генерация ассертов идеевскими аннотациями -- не совсем корректное поведение, всмысле что в общем аннотациям не разрешено влиять на рантайм,

2019-02-26 11:06 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    public E floor(E e) {
Вроде с ним всё было хорошо, можете в истории посмотреть. Но это уже не важно.

2019-02-26 11:09 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class Node<NodeE> {
Кажется единственная возможность это сделать -- сделать его внутренним, иначе ему нужен отдельный параметр, так как он вложенный. Но получивщейся ссылкой я всё равно не пользуюсь, так что не вижу смысла усложнять рантайм.

2019-02-26 11:16 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class TreeSetIterator<ItE> implements Iterator<ItE> {
Да, была такая идея хранить флаг типа reverse. Можно посмотреть на то, что получилось, здесь: 47bf5bfbfa0. По-моему крайне загромождённо.

2019-02-26 11:24 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertThrows(NoSuchElementException.class, () -> emptySet.first());
Имелось в виду, что
`() -> testSet.remove(null)`
означает блок кода, в котором выполняется ` testSet.remove(null)`, причём этот блок кода будет выполнятся внутри `assertThrows`. Логично это понимать как "при выполнении этого блока кода будет кинуто данное исключение". Аналогично
`assertThrows(..., () -> emptySet.first())`
означает, что если написать `emptySet.first()`, то бросится исключение. Если написать ссылку на метод, то эта связь с "что произойдёт, если выполнить данный код" становится не очевидна.

2019-02-26 11:27 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        var singletonTestSet = new TreeSet<String>((a, b) -> 0);
Да, в процессе. Не успел пока. Я не претендовал пока на полное исправление всех замечаний. Которые исправляю, комментирую.

2019-02-26 11:28 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertFalse(testSet.contains("9"));
Да, я понимаю. Просто показалось, что постоянные касты к `(int)` не очень хорошо выглядят.

2019-02-26 11:46 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +                if (!reverse) {
Поправил.

2019-02-26 11:50 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class TreeSetIterator<ItE> implements Iterator<ItE> {
Убрал наследование, сделал один класс с флагом reverse.

2019-02-26 11:52 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private int compare(Object a, Object b) {
Сделано.

2019-02-26 22:11 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private static class Node<NodeE> {
Сделал внутренним и убрал лишний пареметр типа.

2019-02-26 22:35 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        var singletonTestSet = new TreeSet<String>((a, b) -> 0);
Сделано.

2019-02-26 22:35 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            throw new IllegalArgumentException("null elements are prohibited");
Сделано.

2019-02-26 22:55 UTC, kjkrVdxB commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +    void testContains() {
Сделано.

2019-02-27 13:45 UTC, jzuken commented on treeset/build.gradle
> +}
ну вообще разрешено. я же на паре показывал, как программа падает с исключением, если @NotNull нарушается

2019-02-27 13:59 UTC, jzuken requested changes

2019-02-27 13:59 UTC, jzuken commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return before(e, false, true);
жуткие конструкции. если более одного логического аргумента, и их смысл не читается явно из выражения вызова, то в таких местах лучше енумы заводить

2019-02-27 13:59 UTC, jzuken commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private boolean removeInSubtree(Object o, Node subtreeRoot) {
очень длинная функция, надо бы разбить на несколько

2019-02-27 13:59 UTC, jzuken commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        private Node leftChild = null, rightChild = null;
лучше на разные

2019-02-27 18:29 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return before(e, false, true);
Сделано.

2019-02-27 18:29 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        private Node leftChild = null, rightChild = null;
Сделано.

2019-02-27 18:53 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private boolean removeInSubtree(Object o, Node subtreeRoot) {
Укоротил вроде.

2019-02-27 19:02 UTC, kjkrVdxB commented on treeset/build.gradle
> +}
Тут вопрос -- кем разрешено. Ясно, что кто угодно может делать всё что угодно. По мне так использовать аннотации не для того, для чего они были придуманы, да ещё и добавляя во все проекты зависимость на некоторую стороннюю библиотеку и в некотором смысле привязываясь к одной среде разработки -- не то, чего я хочу. Во внешнем интерфейсе стоят проверки в нужных местах, также во всех внутренних вызовах поставил ассерты.

2019-03-03 20:02 UTC, RamSaw commented on treeset/build.gradle
> +}
Ну есть не только от джетов подобные аннотации. Вы не завязываетесь на какую-то конкретную IDE, у Вас же скомпилируется все и запуститься и упадет, если надо. Другое дело Идея плюс ко всему этому сможет провести статический анализ и подсказать вам.

2019-03-03 20:04 UTC, RamSaw commented on treeset/src/test/java/com/example/treeset/TreeSetTest.java
> +        assertThrows(NoSuchElementException.class, () -> emptySet.first());
логика, наверное, в этом есть. Это уже перетекает в халивар, если Вам так более читаемо, то давайте оставим так.

2019-03-03 20:23 UTC, RamSaw requested changes
@kjkrVdx B я посмотрел новые коммиты, написал несколько незначительных комментариев. А так в целом все ок.
По баллам: -1 за аннотации, так как assert вместо них Вы не писали.

2019-03-03 20:23 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        compare(null, null);
а в чем смысл вызова этого метода?

2019-03-03 20:23 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        private Node previousNode; // used in remove()
напишите уж джавадок к полю тогда. К нетривиальным приватным объектам тоже стоит писать джавадоки.

2019-03-03 20:23 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            this.reverse = direction == Direction.REVERSED;
Вы как-то не используете enum тогда. Все равно конвертируете его по сути в boolean. Там выше в методе тоже было. Давайте раз уж у нас enum, то не уходить от него.

2019-03-03 20:23 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            if ((reverse ? nextNode.leftChild : nextNode.rightChild) != null) {
а вот это (reverse ? nextNode.leftChild : nextNode.rightChild) тянет на отдельную функцию. Я вижу эта логика много где используется, давайте сделаем extract method.

2019-03-03 20:23 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            if ((reverse ? nextNode.leftChild : nextNode.rightChild) != null) {
для getBiggest и getLeast тоже применимо.

2019-03-04 22:44 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        compare(null, null);
Чтобы компаратор кидал исключения, в случае, если не поддерживает null, даже когда сравнений не происходит. Так говорит спецификация в TreeSet.

2019-03-04 22:46 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            this.reverse = direction == Direction.REVERSED;
enum используется только для того, чтобы снаружи при вызове было понятно какие где параметры. А внутри функции и без него хорошо было вроде.

2019-03-04 22:53 UTC, kjkrVdxB commented
По поводу снижения за ассерты не совсем согласен. Всё таки такого пункта в списке штрафов нет и явно было сказано, что аннотации не обязательны, про их альтернативы и их обязательность ничего сказано не было. Все внешние нужные исключения у меня кидались. Про то, что либо ассерты, либо аннотации во внутренних вызовах обязательно нужны только сейчас от вас узнал.

2019-03-04 23:01 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        private Node previousNode; // used in remove()
Какому из двух? У обоих вроде названия полностью передают суть.

2019-03-04 23:23 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            if ((reverse ? nextNode.leftChild : nextNode.rightChild) != null) {
Сделано.

2019-03-04 23:23 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +            this.reverse = direction == Direction.REVERSED;
Поправил.

2019-03-05 06:40 UTC, kjkrVdxB commented
Также, отдельным аргументом, ни в коем случае не отказываясь от предыдущего комментария, хочу заметить, что все места, где нужен assert были добавлены после самой первой проверки (и связаны в основном с enum-ами). Так что можно считать, что на момент сдачи задачи во всех необходимых местах слояли assert-ы.

2019-03-05 15:13 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        private Node previousNode; // used in remove()
Добавил к обоим.

2019-03-05 20:03 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        compare(null, null);
Хм, интересно. Ок.

2019-03-05 20:04 UTC, RamSaw commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        private Node previousNode; // used in remove()
Так нет, Вы же коммент там коммент оставили, что в remove используется. Я об этом говорил.

2019-03-05 20:14 UTC, RamSaw approved these changes
@kjkrVdxB на мой взгляд все ок. Передаю слово @jzuken.

2019-03-05 20:18 UTC, RamSaw commented
> По поводу снижения за ассерты не совсем согласен. Всё таки такого пункта в списке штрафов нет и явно было сказано, что аннотации не обязательны, про их альтернативы и их обязательность ничего сказано не было. Все внешние нужные исключения у меня кидались. Про то, что либо ассерты, либо аннотации во внутренних вызовах обязательно нужны только сейчас от вас узнал.

То, что Вы проверяли у public методов null, это правда. Я, к сожалению, не знаю, что Вам говорили на паре, так что лучше пусть Тимофей решит. @jzuken .

2019-03-13 13:30 UTC, jzuken requested changes

2019-03-13 13:30 UTC, jzuken commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return comparator == null ? ((Comparable<? super E>) a).compareTo(b) : comparator.compare((E) a, b);
а лучше проинициализировать компаратор в конструкторе один раз и не делать каждый раз проверки тут

2019-03-13 13:30 UTC, jzuken commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return compare(a, b) * (direction == Direction.NORMAL ? 1 : -1);
вот это дофига нетривиальная логика, к тому же совсем без комментариев. давайте как-то более понятно это реализуем

2019-03-13 13:30 UTC, jzuken commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        compare(null, null);
а я вот не вижу ни спецификацию исключений в этом методе, ни документацию к нему, которая это фиксирует

2019-03-13 13:30 UTC, jzuken commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private E before(E e, OnEqual onEqual, Direction direction) {
вот смотрю я на аргумент `OnEqual onEqual`, и у меня ни малейших идей, что там может храниться, и что это значит. крайне неудачное имя для типа и имени переменной
-0.5

2019-03-15 21:22 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return compare(a, b) * (direction == Direction.NORMAL ? 1 : -1);
Добавил комментариев.

2019-03-15 21:22 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +        return comparator == null ? ((Comparable<? super E>) a).compareTo(b) : comparator.compare((E) a, b);
Вроде сошлись на том, что это плохая идея.

2019-03-15 21:23 UTC, kjkrVdxB commented on treeset/src/main/java/com/example/treeset/TreeSet.java
> +    private E before(E e, OnEqual onEqual, Direction direction) {
Попытался поправить.

2019-03-16 14:58 UTC, merged