Add HW4
kjkrVdxB/Java-HW pull request #5
Opened 2019-02-24 19:31 UTC by kjkrVdxB

2019-03-16 12:53 UTC, jzuken requested changes

2019-03-16 12:53 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBookCliClient.java
> +                                              "0 - exit\n" +
ну, под виндами эти тесты не пройдут, там строки по-другому переводятся. в таких случаях надо использовать System.lineSeparator()

2019-03-16 12:53 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBookCliClient.java
> +                        out.print("Name: ");
буферизуется оно у вас как-то примерно так:

1
aaa
111
1
aaa
222
7
Name: Number: Name: Number: aaa: 111
aaa: 222

2019-03-16 12:53 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            create.executeUpdate("create table if not exists Person " +
такие штуки лучше из файла грузить

2019-03-16 12:53 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        insertPersonIfNotExists(name);
а если такая запись уже есть, оно просто молчит. нехорошо
-0.5

2019-03-16 12:53 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
один в один копипаста из getNamesByNumber()
-1

2019-03-16 12:53 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        var updateString = "update or replace Entry set PersonId = (select Id from Person where Name = ?) where " +
а тут копипаста с updateNumber()

2019-03-16 12:56 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        insertPersonIfNotExists(name);
Это задокументировано чуть выше и по заданию никакое поведение не задано.

2019-03-16 12:57 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBookCliClient.java
> +                        out.print("Name: ");
Так и есть. Но я думаю UX важнее.

2019-03-16 13:02 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
Считаю, что так и должно быть. По заданию хотели всю логику по организации данных перенести на DB. Обработка общения с DB изолирована на уровне методов и крайне коротка. Не вижу смысла это выносить в отдельные методы.

2019-03-16 13:03 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            create.executeUpdate("create table if not exists Person " +
Не понял, о чём вы.

2019-03-16 13:17 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        var updateString = "update or replace Entry set PersonId = (select Id from Person where Name = ?) where " +
В каком именно месте? Строка запроса другая. Метод insertPersonIfNotExists другой. См. комментарий выше об изоляции работы с DB.

2019-03-16 13:28 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBookCliClient.java
> +                                              "0 - exit\n" +
Исправлено

2019-03-16 14:48 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        insertPersonIfNotExists(name);
в ТЗ редко попадают все те побочные ветки работы с пользователем. но это не значит, что пользователя надо игнорить и неуважать

2019-03-16 14:48 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
что значит разные? там здоровый кусок кода просто повторяется досимвольно

2019-03-16 14:48 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        var updateString = "update or replace Entry set PersonId = (select Id from Person where Name = ?) where " +
Прямо совпадающий код составляют только проверки параметров (и то не пльностью) и проверки исключений, но они будут повторятся всегда и с этим ничего не сделать. Вам не нравится, то, что у них общий вызов connection.prepareStatement(...) и дальше три параметра? Не выглядит как то, что стоит выносить в общий метод.

2019-03-16 14:48 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            create.executeUpdate("create table if not exists Person " +
я про схему БД

2019-03-16 14:59 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
Вот запросы делить я точно не буду. Я по началу хотел добавить методы вида getIdByName и так далее, но подумал, что по заданию это не приветствуется. Я считаю что в задании хотят, чтобы работа с данными полностью выполнялась базой данных, поэтому например нельзя выбрать всё и потом самому обработать. В частности выносить Id в пространство джавы я считаю тоже не приемлемо.

2019-03-16 15:02 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        insertPersonIfNotExists(name);
Не очень понимаю, за что тогда снижение баллов. В моём понимание данное повидение имеет место на жизнь, корректно реализовано, задокументировано, и не запрещено заданием

2019-03-16 15:04 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            create.executeUpdate("create table if not exists Person " +
В каком смысле грузить из файла? Хранить пустую DB и из неё брать схему?

2019-03-16 15:06 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
Или вы имеете в виду код преобразования результата в  список? Про это я ещё могу понять, но в updateNumber такой проблемы нет.

2019-03-18 18:30 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        insertPersonIfNotExists(name);
При добавлении записи которая уже находится в таблице теперь выводится сообщение

2019-03-18 18:31 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
Код преобразования в список вынес в отдельный метод

2019-03-20 09:44 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
всё, что делает код в этом методе -- это формирует запрос, препроцессит его, а потом выполняет его, получает результат, превращает его в набор строк, который возвращает наружу.  метод getNamesByNumber() делает ровно то же самое, ну только запрос другой. если вы не видите, что дальше делается одно и то же высокоуровневое действие, которое запросто может потребоваться ещё раз в другом месте, это печально

2019-03-20 09:46 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            create.executeUpdate("create table if not exists Person " +
просто SQL-скрипт хранить в файле

2019-03-20 09:48 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        insertPersonIfNotExists(name);
ну а моём понимании с точки зрения пользователя такого поведения стоит не допускать

2019-03-20 09:49 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +        var updateString = "update or replace Entry set PersonId = (select Id from Person where Name = ?) where " +
ладно, здесь действительно добавлять лишнюю зависимость в коде не стоит, наверное

2019-03-20 10:37 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
Это-то я как раз понимаю. И с удоволствием это всё вынес бы в метод и не городил повторяющиеся проверки исключений во всех методах. Но JDBC API устроено так, что по сути то, что написано и предполагается писать так. Там нет препроцессинга, есть просто добавление параметров в запрос. И это добавление в JDBC API делается через setString. Говорить, что использование этого API - дубликация кода - и надо бы поверх него написать красивую оболочку, я считаю странно.
Частная причина - лямбды не умеют обьявлять проверяемые исключения, коим SQLException является. Поэтому блок try-catch в отдельный метод не вынести.

2019-03-20 10:45 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
всё ещё не вижу ни одного убедительного аргумента против метода executeQuery(), который делает всё кроме формирования строки queryString

2019-03-20 11:17 UTC, kjkrVdxB commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
Написана же проблема с исключениями. И она не решается.

2019-03-20 11:23 UTC, jzuken commented on phonebook/src/main/java/com/example/phonebook/PhoneBook.java
> +            query.setString(1, name);
так не надо придумывать себе лишних проблем, там лямбды вообще нафиг не нужны

2019-03-21 15:26 UTC, merged