Add HW7
kjkrVdxB/Java-HW pull request #9
Opened 2019-04-30 00:39 UTC by kjkrVdxB

2019-05-02 12:44 UTC, jzuken requested changes

2019-05-02 12:44 UTC, jzuken commented on threadpool/src/main/java/com/example/threadpool/FixedThreadPool.java
> +                    // NB: we do not clean up the queue (and associated tasks in thenApplyLists) for the following
мне всё же кажется, что от метода с таким названием ожидаешь полноценного завершения всего, то есть возврат управления, только когда все потоки остановились. это, понятно, при условии, что все потоки адекватно реагируют на interrupt. и какого-то слишком большого усложнения тут не вижу

2019-05-03 14:46 UTC, kjkrVdxB commented on threadpool/src/main/java/com/example/threadpool/FixedThreadPool.java
> +                    // NB: we do not clean up the queue (and associated tasks in thenApplyLists) for the following
>ожидаешь полноценного завершения всего, то есть возврат управления, только когда все потоки остановились
Ну, например, от стандартных пулов этого не ожидают и они этого не гарантируют.

Условие, что потоки нормально реагируют на interrupt крайне странно. Этот как минимум расходится с мировосприятием стандартных пулов и семантикой их shutdownNow() (best effort через interrupt() и всё). Но если верить, что все supplierы нормально реагируют на interrupt, то описанное вами поведение и правда просто реализовать.

Но тут скорее даже не про это написано.
Этот коментарий про то, что мы ничего не делаем с тасками, ещё не начавшими исполнятся. Не хочется повторять то, что написано в комментарии, мне кажется там достаточно подробно описано, почему эту обработку скорее всего не хотели в задании. И именно она всё крайне усложняет.

2019-05-03 14:56 UTC, kjkrVdxB commented on threadpool/src/main/java/com/example/threadpool/FixedThreadPool.java
> +                    // NB: we do not clean up the queue (and associated tasks in thenApplyLists) for the following
На всякий случай, по поводу ожидания завершения в документации к shutdownNow() написано:
>This method does not wait for actively executing tasks to terminate. Use awaitTermination to do that.
There are no guarantees beyond best-effort attempts to stop processing actively executing tasks. For example, typical implementations will cancel via Thread.interrupt(), so any task that fails to respond to interrupts may never terminate.

2019-05-03 15:12 UTC, jzuken commented on threadpool/src/main/java/com/example/threadpool/FixedThreadPool.java
> +                    // NB: we do not clean up the queue (and associated tasks in thenApplyLists) for the following
так если таски не начали исполняться, то и не надо их трогать

2019-05-03 16:04 UTC, kjkrVdxB commented on threadpool/src/main/java/com/example/threadpool/FixedThreadPool.java
> +                    // NB: we do not clean up the queue (and associated tasks in thenApplyLists) for the following
Сделал так, чтобы shutdown() ждал завершения всех потоков.

2019-05-03 16:04 UTC, kjkrVdxB commented on threadpool/src/main/java/com/example/threadpool/FixedThreadPool.java
> +                    // NB: we do not clean up the queue (and associated tasks in thenApplyLists) for the following
Сделал так, чтобы shutdown() ждал завершения всех потоков.

2019-05-11 09:41 UTC, merged